import { ApiProviderConfig } from '../models/api-provider.model';

export const API_PROVIDER_CONFIGS: readonly ApiProviderConfig[] = [
    {
        id: 'github',
        displayName: 'GitHub',
        category: 'code-hosting',
        baseUrl: 'https://api.github.com',
        documentationUrl: 'https://docs.github.com/en/rest',
        enabled: true,
        auth: {
            requiresAuth: false,
            supportsOptionalAuth: true,
            tokenStorageKey: 'devpulse.api.github.token',
            authHeaderName: 'Authorization',
            authHeaderPrefix: 'Bearer',
        },
        rateLimit: {
            requestsPerWindow: 60,
            windowInSeconds: 3600,
            supportsRateLimitHeaders: true,
            requiresCooldownHandling: true,
        },
        defaultTimeoutMs: 15000,
    },
    {
        id: 'stackExchange',
        displayName: 'Stack Exchange',
        category: 'qa',
        baseUrl: 'https://api.stackexchange.com/2.3',
        documentationUrl: 'https://api.stackexchange.com/docs',
        enabled: true,
        auth: {
            requiresAuth: false,
            supportsOptionalAuth: false,
        },
        rateLimit: {
            requestsPerWindow: 300,
            windowInSeconds: 86400,
            supportsRateLimitHeaders: true,
            requiresCooldownHandling: true,
        },
        defaultTimeoutMs: 15000,
    },
    {
        id: 'devTo',
        displayName: 'DEV Community',
        category: 'articles',
        baseUrl: 'https://dev.to/api',
        documentationUrl: 'https://developers.forem.com/api',
        enabled: true,
        auth: {
            requiresAuth: false,
            supportsOptionalAuth: true,
            tokenStorageKey: 'devpulse.api.devto.token',
            authHeaderName: 'api-key',
        },
        rateLimit: {
            requestsPerWindow: 10,
            windowInSeconds: 30,
            supportsRateLimitHeaders: false,
            requiresCooldownHandling: true,
        },
        defaultTimeoutMs: 15000,
    },
    {
        id: 'hackerNews',
        displayName: 'Hacker News',
        category: 'news',
        baseUrl: 'https://hacker-news.firebaseio.com/v0',
        documentationUrl: 'https://github.com/HackerNews/API',
        enabled: true,
        auth: {
            requiresAuth: false,
            supportsOptionalAuth: false,
        },
        rateLimit: {
            requestsPerWindow: 100,
            windowInSeconds: 60,
            supportsRateLimitHeaders: false,
            requiresCooldownHandling: false,
        },
        defaultTimeoutMs: 15000,
    },
    {
        id: 'reddit',
        displayName: 'Reddit',
        category: 'community',
        baseUrl: 'https://www.reddit.com',
        documentationUrl: 'https://www.reddit.com/dev/api',
        enabled: false,
        auth: {
            requiresAuth: false,
            supportsOptionalAuth: true,
            tokenStorageKey: 'devpulse.api.reddit.token',
            authHeaderName: 'Authorization',
            authHeaderPrefix: 'Bearer',
        },
        rateLimit: {
            requestsPerWindow: 100,
            windowInSeconds: 60,
            supportsRateLimitHeaders: true,
            requiresCooldownHandling: true,
        },
        defaultTimeoutMs: 15000,
    },
    {
        id: 'ai',
        displayName: 'AI Provider',
        category: 'ai',
        baseUrl: '',
        documentationUrl: '',
        enabled: false,
        auth: {
            requiresAuth: false,
            supportsOptionalAuth: true,
            tokenStorageKey: 'devpulse.api.ai.token',
            authHeaderName: 'Authorization',
            authHeaderPrefix: 'Bearer',
        },
        rateLimit: {
            requestsPerWindow: 10,
            windowInSeconds: 60,
            supportsRateLimitHeaders: true,
            requiresCooldownHandling: true,
        },
        defaultTimeoutMs: 30000,
    },
];